services:
  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: x3akqrtww
      POSTGRES_USER: postgres
      POSTGRES_DB: auth_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8888:8080"
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongodata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodata:
  postgresdata: