spring:
  application:
    name: user

  data:
    mongodb:
      uri: mongodb://admin:pass@localhost:27017/
      host: localhost
      username: admin
      password: pass
      database: user_profile_db


server:
  port: 9091
  servlet:
    context-path: /api