server:
  port: 9090
  servlet:
    context-path: /api

spring:
  application:
    name: auth

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: x3akqrtww
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true
    disable-swagger-default-url: true
    doc-expansion: none
  show-actuator: true